name: Unit Tests

on: pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
      JIRA_HOST: ${{ secrets.JIRA_HOST }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
